application:
 name: "stanlib-system-warehouse.api"
api:
 name: "stanlib-system-warehouse.api"
 id: "0"
 version: "v1"
 http:
  listener:
   path: "/v1/*"
   host: "0.0.0.0"
   port: "8094"

jks:
  alias: "api-lb-test"